import { Inter } from 'next/font/google'
import {Providers} from "./providers";
import {Header} from "../shared/Header/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body>
          <Providers>
              <Header/>
            {children}
          </Providers>
        </body>
      </html>
  )
}
